name: 'Close stale issues and PRs'

on:
  schedule:
    - cron: '21 1 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: "Debugging dry run"

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          operations-per-run: 50
          stale-issue-message: 'This issue is stale because no answers have been provided in the last 14 days. If there are still no answers within 7 days then the issue will be closed.'
          stale-pr-message: 'This PR is stale because no answers have been provided in the last 14 days. If there are still no answers within 7 days then the PR will be closed.'
          close-issue-message: 'This issue was closed because no answers were provided within 21 days.'
          close-pr-message: 'This PR was closed because no answers were provided within 21 days.'
          days-before-issue-stale: 14
          days-before-pr-stale: 14
          days-before-issue-close: 7
          days-before-pr-close: 7
          any-of-labels: 'awaiting-answers'
